# Generated by Django 5.1 on 2024-09-05 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmission',
            name='submission',
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='submissions',
            field=models.ManyToManyField(related_name='user_submissions', to='app_v1.submission'),
        ),
        migrations.AlterField(
            model_name='userenrollment',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 5, 1, 21, 54, 226117, tzinfo=datetime.timezone.utc)),
        ),
    ]
