# Generated by Django 5.1 on 2024-09-07 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0002_remove_usersubmission_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userenrollment',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 12, 40, 29, 945568, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userenrollment',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('trial', 'Trial'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('expired', 'Expired')], default='pending', max_length=50),
        ),
    ]
