# Generated by Django 5.1 on 2024-09-07 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0003_course_content_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenrollment',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 12, 41, 0, 331606, tzinfo=datetime.timezone.utc)),
        ),
    ]
