# Generated by Django 5.1 on 2024-09-08 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0004_alter_userenrollment_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userenrollment',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 13, 37, 22, 528280, tzinfo=datetime.timezone.utc)),
        ),
    ]
