# Generated by Django 5.1 on 2024-09-11 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0006_remove_course_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenrollment',
            name='is_check_expiration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userenrollment',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 18, 0, 45, 31, 352397, tzinfo=datetime.timezone.utc)),
        ),
    ]
