# Generated by Django 5.1 on 2024-09-13 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0007_userenrollment_is_check_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='url_doc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userenrollment',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 0, 36, 26, 742886, tzinfo=datetime.timezone.utc)),
        ),
    ]
