# Generated by Django 5.1 on 2024-09-13 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0008_lesson_url_doc_alter_userenrollment_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userenrollment',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 9, 6, 17, 636395, tzinfo=datetime.timezone.utc)),
        ),
    ]
