# Generated by Django 5.1 on 2024-09-13 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0009_lesson_is_trial_alter_userenrollment_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='url_doc',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='url_video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userenrollment',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 9, 21, 45, 727759, tzinfo=datetime.timezone.utc)),
        ),
    ]
